# Generally you would create a properties file per spring profile for easier management between ENVs for this using no profile is ok
# as its only planned to run locally

spring.application.name=disco
spring.datasource.url=jdbc:postgresql://localhost:5432/discocactus
spring.datasource.username=postgres
spring.datasource.password=reallystrongpassword
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Letting JPA create the db and tables for the project.
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8085